### ISSUE TITLE
[offtopic] I think I've lost your relevant e-mail

### ISSUE THREAD

**Issue by dodikk** [jackyf/squco#1]
Sorry for offtopic but...
Unfortunately, I've lost your relevant e-mail address (or you have not given one to me) and this offtopic seems to be the only way to get in touch again. Please drop me a line by e-mail if you have some time.

P.S. Вспомним Йоллупукке и пузатого Стэннэра.

**Comment by jackyf** [comment]
Hmm, perhaps my mail from 25.12.2018 got lost. Re-sent to your GitHub e-mail.
